
name: 'jaffle_shop'
version: '0.1'
profile: 'jaffle_shop'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

dispatch:
  - macro_namespace: dbt_external_tables
    search_order: ['dbt', 'dbt_external_tables']

models:
  jaffle_shop:
      +pre-hook: "set firebolt_dont_wait_for_upload_to_s3=1" # WARNING: alpha feature
      materialized: table
      staging:
        materialized: table

models:
  jaffle_shop:
    
seeds:
  jaffle_shop:
    +pre-hook: "set firebolt_dont_wait_for_upload_to_s3=1" # WARNING: alpha feature
    +quote_columns: true
    raw_orders:
      +column_types:
        order_date: TEXT